-- =============================================================================
-- PASSWORD BREACH MONITORING (PBM) DATABASE — MYSQL & MARIADB DUMP SCRIPT
-- Target Database: `Case-Study`
-- Compatibility: MySQL 5.7+, MySQL 8.0+, MariaDB 10.3+
-- Encoding: utf8mb4 / utf8mb4_unicode_ci
-- =============================================================================

-- Step 1: Create and select the database `Case-Study`
CREATE DATABASE IF NOT EXISTS `Case-Study` 
  DEFAULT CHARACTER SET utf8mb4 
  COLLATE utf8mb4_unicode_ci;

USE `Case-Study`;

-- Step 2: Drop existing tables if re-initializing
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `sources`;
DROP TABLE IF EXISTS `case_studies`;
DROP TABLE IF EXISTS `breaches`;
SET FOREIGN_KEY_CHECKS = 1;

-- -----------------------------------------------------------------------------
-- Table structure for `breaches`
-- -----------------------------------------------------------------------------
CREATE TABLE `breaches` (
  `id` VARCHAR(64) NOT NULL,
  `breach_name` VARCHAR(255) NOT NULL,
  `organization` VARCHAR(255) NOT NULL,
  `industry` VARCHAR(100) NOT NULL,
  `breach_date` VARCHAR(30) NOT NULL,
  `discovery_date` VARCHAR(30) NOT NULL,
  `affected_records` BIGINT NOT NULL,
  `severity` VARCHAR(50) NOT NULL,
  `breach_type` VARCHAR(100) NOT NULL,
  `attack_vector` VARCHAR(100) NOT NULL,
  `data_exposed` TEXT NOT NULL,
  `root_cause` TEXT NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_breach_date` (`breach_date`),
  INDEX `idx_severity` (`severity`),
  INDEX `idx_industry` (`industry`),
  INDEX `idx_attack_vector` (`attack_vector`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- Table structure for `case_studies`
-- -----------------------------------------------------------------------------
CREATE TABLE `case_studies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `breach_id` VARCHAR(64) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `subtitle` VARCHAR(255) NOT NULL,
  `date` VARCHAR(30) NOT NULL,
  `severity` VARCHAR(50) NOT NULL,
  `executive_summary` TEXT NOT NULL,
  `timeline_json` MEDIUMTEXT NOT NULL,
  `response` TEXT NOT NULL,
  `attack_vector_tags` TEXT NOT NULL,
  `root_cause` TEXT NOT NULL,
  `data_exposed_tags` TEXT NOT NULL,
  `impact_metrics` TEXT NOT NULL,
  `lessons_learned` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_cs_breach_id` (`breach_id`),
  CONSTRAINT `fk_case_studies_breach` FOREIGN KEY (`breach_id`) REFERENCES `breaches` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- Table structure for `sources`
-- -----------------------------------------------------------------------------
CREATE TABLE `sources` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `breach_id` VARCHAR(64) NOT NULL,
  `source_type` VARCHAR(100) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `authority_or_publisher` VARCHAR(255) NOT NULL,
  `url` TEXT NOT NULL,
  `publication_year` VARCHAR(30) NOT NULL,
  `citation_note` TEXT,
  PRIMARY KEY (`id`),
  INDEX `idx_sources_breach_id` (`breach_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -----------------------------------------------------------------------------
-- Insert 80+ Authentic Real-World Breach Records
-- -----------------------------------------------------------------------------
INSERT INTO `breaches` (`id`, `breach_name`, `organization`, `industry`, `breach_date`, `discovery_date`, `affected_records`, `severity`, `breach_type`, `attack_vector`, `data_exposed`, `root_cause`, `status`) VALUES
('PBM-EQFX', 'Equifax Credit Bureau Apache Struts Intrusion', 'Equifax', 'Finance', '2017-05-13', '2017-07-29', 147000000, 'Critical', 'Database Exposure', 'Unpatched vulnerability', 'Social Security Numbers, Full names, Dates of birth, Home addresses, Driver license numbers, Credit card numbers', 'Unpatched Apache Struts vulnerability (CVE-2017-5638) on dispute portal, expired SSL inspection certificates delaying detection.', 'Resolved'),
('PBM-CPO1', 'Capital One Cloud Storage SSRF Exfiltration', 'Capital One', 'Finance', '2019-03-22', '2019-07-17', 106000000, 'Critical', 'API Exfiltration', 'Cloud misconfiguration', 'Credit card applications, Social Security Numbers, Linked bank account numbers, Credit scores, Transaction records', 'Misconfigured open-source Web Application Firewall (ModSecurity on EC2) vulnerable to SSRF, allowing metadata service access and IAM role token theft.', 'Resolved'),
('PBM-YAHO', 'Yahoo! Global User Account Database Breach', 'Yahoo!', 'Technology', '2013-08-01', '2016-09-22', 3000000000, 'Critical', 'Credential Leak', 'Phishing', 'Usernames, Email addresses, Telephone numbers, MD5 / bcrypt password hashes, Dates of birth, Security questions and answers', 'Spear phishing campaign compromised internal corporate network; attackers minted forged cookies to access user email accounts without passwords.', 'Resolved'),
('PBM-LPAS', 'LastPass Cloud Backup & Vault Exfiltration', 'LastPass', 'Technology', '2022-08-12', '2022-11-30', 30000000, 'Critical', 'Source Code Leak', 'Supply chain', 'Encrypted password vaults, Website URLs, Account usernames, Billing addresses, End-user telephone numbers', 'Compromise of a senior DevOps engineer\'s home media server (Plex CVE-2020-5741) captured AWS cloud backup access tokens and storage decryption keys.', 'Resolved'),
('PBM-23ME', '23andMe DNA Relatives Credential Stuffing', '23andMe', 'Healthcare', '2023-10-01', '2023-10-06', 6900000, 'High', 'Credential Leak', 'Credential stuffing', 'Genetic ancestry reports, Family tree linkages, Full names, Birth years, Geographical locations, Self-reported health traits', 'Automated credential stuffing against accounts lacking Multi-Factor Authentication (MFA), followed by scraping opt-in DNA Relatives feature networks.', 'Resolved'),
('PBM-MRRT', 'Marriott Starwood Guest Reservation Intrusion', 'Marriott International', 'Transport', '2014-07-01', '2018-09-08', 339000000, 'Critical', 'Database Exposure', 'Stolen session', 'Passport numbers, Contact info, Loyalty account details, Travel itinerary, Encrypted payment card numbers', 'Undetected RAT (Remote Access Trojan) and Mimikatz credential dumping active on legacy Starwood network acquired prior to IT integration.', 'Resolved'),
('PBM-TRGT', 'Target Corporation HVAC Vendor POS Intrusion', 'Target', 'Retail', '2013-11-27', '2013-12-12', 110000000, 'Critical', 'Database Exposure', 'Phishing', 'Credit & debit card magnetic stripe data, Customer names, Mailing addresses, Phone numbers, Email addresses', 'Spear phishing email compromised HVAC vendor (Fazio Mechanical) credentials; flat network design permitted lateral movement to Point-of-Sale registers.', 'Resolved'),
('PBM-UBER', 'Uber GitHub Credential & AWS S3 Exfiltration', 'Uber Technologies', 'Transport', '2016-10-01', '2016-11-10', 57000000, 'High', 'API Exfiltration', 'API Key leak', 'Driver license numbers, Rider names, Email addresses, Mobile phone numbers', 'Hardcoded AWS credentials embedded in a private GitHub code repository accessed by attackers to download S3 database archives.', 'Resolved'),
('PBM-SLRW', 'SolarWinds Orion SUNBURST Supply Chain Backdoor', 'SolarWinds', 'Technology', '2020-03-01', '2020-12-12', 18000, 'Critical', 'Supply Chain Breach', 'Supply chain', 'Internal emails, System configuration files, Network topologies, SAML signing certificates', 'Nation-state threat actor injected malicious backdoor (SUNBURST / Solorigate) directly into Orion software build pipeline, digitally signing weaponized updates.', 'Resolved'),
('PBM-CHNG', 'Change Healthcare Citrix Portal Ransomware', 'Change Healthcare (UnitedHealth)', 'Healthcare', '2024-02-21', '2024-02-21', 100000000, 'Critical', 'Database Exposure', 'Stolen session', 'Patient medical histories, Diagnosis codes, Health insurance claim numbers, Social Security Numbers, Billing records', 'Stolen corporate credentials used to log into an external Citrix remote-access portal that lacked Multi-Factor Authentication (MFA).', 'Resolved'),
('PBM-SNOW', 'Ticketmaster & Live Nation Snowflake Exfiltration', 'Ticketmaster', 'Technology', '2024-05-27', '2024-05-28', 560000000, 'Critical', 'Database Exposure', 'Credential stuffing', 'Customer names, Email addresses, Billing addresses, Telephone numbers, Partial payment card digits & expiration dates', 'Contractor workstation infected with Lumma/RedLine infostealer malware, yielding single-factor Snowflake database credentials without MFA enforcement.', 'Resolved'),
('PBM-CNVA', 'Canva Graphic Design Gnosticplayers Breach', 'Canva', 'Technology', '2019-05-24', '2019-05-24', 137000000, 'High', 'Credential Leak', 'Zero-day exploit', 'Usernames, Real names, Email addresses, Salted bcrypt password hashes, City/Country locations', 'Attacker Gnosticplayers exploited an internal administrative gateway vulnerability, exfiltrating user database snapshots before detection.', 'Resolved'),
('PBM-ADBE', 'Adobe Systems Customer Database & Source Exfiltration', 'Adobe Systems', 'Technology', '2013-10-03', '2013-10-03', 153000000, 'Critical', 'Credential Leak', 'Zero-day exploit', 'Adobe IDs, Symmetrically encrypted password strings, Password hints in plaintext, Credit card numbers', 'Compromised backup server storing passwords encrypted with symmetric 3DES instead of one-way salted hashes, alongside proprietary product source code.', 'Resolved'),
('PBM-LNKD', 'LinkedIn Unsalted SHA-1 Member Password Leak', 'LinkedIn', 'Technology', '2012-05-05', '2012-06-05', 164000000, 'High', 'Credential Leak', 'SQL Injection', 'Email addresses, Unsalted SHA-1 password hashes', 'SQL injection vulnerability on internal member authentication service and failure to apply cryptographic salt before SHA-1 hashing.', 'Resolved'),
('PBM-DBOX', 'Dropbox Corporate Password Reuse Incident', 'Dropbox', 'Technology', '2012-07-01', '2016-08-30', 68000000, 'Medium', 'Credential Leak', 'Credential stuffing', 'User email addresses, Salted bcrypt & SHA-1 password hashes', 'Dropbox employee reused their LinkedIn password, allowing attackers to access internal Dropbox project documents and user records.', 'Resolved'),
('PBM-HDPT', 'Home Depot POS Perimeter Malware Incident', 'Home Depot', 'Retail', '2014-09-02', '2014-09-02', 56000000, 'High', 'Database Exposure', 'Phishing', 'Payment card numbers, Customer email addresses, Expiration dates, Cardholder names', 'Third-party vendor credentials stolen via phishing, followed by deployment of custom memory-scraping malware across 7,500 self-checkout terminals.', 'Resolved'),
('PBM-PSN1', 'Sony PlayStation Network Global Outage & Intrusion', 'Sony PlayStation Network', 'Media', '2011-04-17', '2011-04-20', 77000000, 'Critical', 'Database Exposure', 'Unpatched vulnerability', 'Names, Physical addresses, Email addresses, Birthdates, PSN login passwords, Credit card data', 'Unpatched Apache application server and unsegmented network architecture allowed attackers to pivot directly into master customer databases.', 'Resolved'),
('PBM-EBAY', 'eBay Corporate Employee Credential Compromise', 'eBay', 'Retail', '2014-05-21', '2014-05-21', 145000000, 'High', 'Credential Leak', 'Phishing', 'Customer names, Encrypted passwords, Email addresses, Physical addresses, Phone numbers, Dates of birth', 'Phishing attack compromised log-in credentials of a small number of corporate employees, allowing unauthorized lateral database access.', 'Resolved'),
('PBM-ANTH', 'Anthem Healthcare DBA Credential Spear Phishing', 'Anthem Health', 'Healthcare', '2015-01-29', '2015-01-29', 78800000, 'Critical', 'Database Exposure', 'Phishing', 'Social Security Numbers, Full names, Medical ID numbers, Dates of birth, Home addresses, Employment details', 'Spear phishing email tricked a database administrator into entering credentials, which nation-state threat actors used to query unencrypted data warehouse.', 'Resolved'),
('PBM-TMOB', 'T-Mobile USA Unprotected Testing Router Intrusion', 'T-Mobile', 'Telecommunications', '2021-08-16', '2021-08-16', 54000000, 'High', 'Database Exposure', 'Access policy error', 'Social Security Numbers, Full names, Driver license data, IMEI / IMSI device numbers, Account PINs', 'Exposed testing GPRS router accessible without adequate firewall segmentation permitted SSH brute-force attack into core data center servers.', 'Resolved'),
('PBM-TWTR', 'Twitter / X User Identifier Enumeration API Leak', 'Twitter / X', 'Media', '2022-07-21', '2022-08-05', 200000000, 'Medium', 'API Exfiltration', 'Zero-day exploit', 'Email addresses, Screen names, Account creation dates, Follower counts, Verified status', 'Bug introduced in June 2021 authorization update allowed anyone to submit email addresses to API and receive matching Twitter user ID.', 'Resolved'),
('PBM-RCKY', 'RockYou Plaintext Social Gaming Password Dump', 'RockYou', 'Technology', '2009-12-14', '2009-12-14', 32000000, 'High', 'Credential Leak', 'SQL Injection', 'Plaintext passwords, User email addresses, Social application usernames', 'Classic SQL injection vulnerability on web login parameter, compounded by storing millions of user passwords in unencrypted cleartext.', 'Resolved'),
('PBM-MGMR', 'MGM Resorts Okta Help Desk Vishing Ransomware', 'MGM Resorts International', 'Media', '2023-09-10', '2023-09-10', 10000000, 'High', 'MFA Bypass', 'Phishing', 'Full names, Contact information, Driver license numbers, Social Security Numbers, Passport numbers', 'Social engineering / voice phishing (vishing) of IT Help Desk impersonating employees, allowing Scattered Spider to reset Okta MFA credentials.', 'Resolved'),
('PBM-BAIR', 'British Airways Magecart Digital Payment Skimmer', 'British Airways', 'Transport', '2018-09-06', '2018-09-06', 500000, 'High', 'API Exfiltration', 'Supply chain', 'Credit card numbers, CVV security codes, Expiration dates, Cardholder names, Billing addresses', 'Magecart threat actors modified third-party JavaScript file on payment booking pages, silently skimming live credit card submissions.', 'Resolved'),
('PBM-ZYNG', 'Zynga Games Words With Friends Credential Spill', 'Zynga', 'Media', '2019-09-12', '2019-09-12', 218000000, 'High', 'Credential Leak', 'Zero-day exploit', 'Usernames, Email addresses, Salted SHA-1 password hashes, Phone numbers, Facebook IDs', 'Hacker Gnosticplayers breached cloud database cluster holding legacy Words with Friends and Draw Something account credentials.', 'Resolved'),
('PBM-EXCT', 'Exactis Marketing Public Elasticsearch Cluster', 'Exactis', 'Technology', '2018-06-01', '2018-06-01', 340000000, 'Critical', 'Database Exposure', 'Cloud misconfiguration', 'Home addresses, Phone numbers, Email addresses, Personal interests, Household habits, Children profiles', 'Marketing data broker left a 2-terabyte Elasticsearch database server exposed to the public internet with zero firewall or authentication rules.', 'Resolved'),
('PBM-MYHR', 'MyHeritage Genealogy Hash Dump Disclosure', 'MyHeritage', 'Healthcare', '2018-06-04', '2018-06-04', 92000000, 'Medium', 'Credential Leak', 'Access policy error', 'Email addresses, Salted SHA-1 password hashes', 'A security researcher found a customer account file containing hashed passwords stored on an external private server outside standard cloud boundary.', 'Resolved'),
('PBM-TWCH', 'Twitch Interactive Source Code & Creator Payout Leak', 'Twitch Interactive', 'Media', '2021-10-06', '2021-10-06', 125000000, 'High', 'Source Code Leak', 'Cloud misconfiguration', 'Complete Git source code repository, Creator payout records, Internal security tools, Unreleased Amazon Games SDKs', 'Server configuration change allowed a malicious actor to download entire proprietary codebases and financial payout databases.', 'Resolved'),
('PBM-OKTA', 'Okta Sitel Customer Support Sub-Processor Breach', 'Okta', 'Technology', '2022-01-21', '2022-03-22', 366, 'High', 'Session Hijack', 'Supply chain', 'Customer support case screenshots, Internal tenant configurations, SuperUser diagnostic access', 'Lapsus$ cybercrime group compromised an engineer workstation at third-party customer service vendor Sitel/Sykes, gaining temporary tenant visibility.', 'Resolved'),
('PBM-OPTS', 'Optus Unauthenticated API Endpoint Data Exfiltration', 'Optus Telecom', 'Telecommunications', '2022-09-22', '2022-09-22', 9800000, 'Critical', 'API Exfiltration', 'Legacy endpoint', 'Passport numbers, Driver license numbers, Medicare card numbers, Full names, Dates of birth, Residential addresses', 'A test API endpoint connected to live customer databases was inadvertently left open to the public internet without requiring authentication tokens.', 'Resolved'),
('PBM-MOVT', 'MOVEit Transfer Cl0p SQL Injection Extortion Wave', 'Progress Software (MOVEit)', 'Technology', '2023-05-27', '2023-05-31', 62000000, 'Critical', 'Database Exposure', 'Zero-day exploit', 'Corporate payroll files, Employee Social Security Numbers, Pension data, Healthcare records, Government contractor files', 'Critical zero-day SQL injection vulnerability (CVE-2023-34362) in MOVEit managed file transfer application exploited by Cl0p ransomware syndicate.', 'Resolved'),
('PBM-AMAD', 'Ashley Madison Customer Database Leak by The Impact Team', 'Ashley Madison', 'Media', '2015-07-12', '2015-07-19', 37000000, 'Critical', 'Database Exposure', 'Insider Threat', 'Customer real names, Credit card transaction logs, Physical addresses, Email addresses, Bcrypt & MD5 password hashes', 'Compromise of internal server infrastructure and source code repositories, enabling mass dump of entire production databases.', 'Resolved'),
('PBM-HRTL', 'Heartland Payment Systems Card Processing Sniffer', 'Heartland Payment Systems', 'Finance', '2008-12-26', '2009-01-20', 130000000, 'Critical', 'Database Exposure', 'SQL Injection', 'Payment card numbers, Cardholder names, Expiration dates, Magnetic stripe Track 1 & 2 data', 'SQL injection vulnerability exploited to install packet sniffer malware inside payment authorization corporate processing networks.', 'Resolved'),
('PBM-QORA', 'Quora Internal Database System Unauthorized Access', 'Quora', 'Technology', '2018-11-30', '2018-11-30', 100000000, 'High', 'Database Exposure', 'Access policy error', 'Account names, Email addresses, Salted bcrypt password hashes, Direct messages, Personalization settings', 'Malicious third party gained unauthorized administrative access to internal production database cluster.', 'Resolved'),
('PBM-CHGG', 'Chegg Educational Platform User Credential Exfiltration', 'Chegg', 'Education', '2018-09-19', '2018-09-19', 40000000, 'Medium', 'Credential Leak', 'Cloud misconfiguration', 'Customer names, Email addresses, Shipping addresses, Salted passwords', 'Unauthorized party gained access to company databases containing user records hosted on cloud infrastructure.', 'Resolved'),
('PBM-DBSM', 'Dubsmash Video Social Network Hash Exposure', 'Dubsmash', 'Media', '2018-12-01', '2019-02-11', 162000000, 'High', 'Credential Leak', 'Zero-day exploit', 'Email addresses, Salted SHA-256 password hashes, Usernames, Dates of birth', 'Database breach by Gnosticplayers obtaining user tables and listing collections for sale on Dream Market dark web portal.', 'Resolved'),
('PBM-EVTE', 'Evite Automated Backup File Dark Web Exposure', 'Evite', 'Media', '2019-05-01', '2019-05-01', 100000000, 'High', 'Database Exposure', 'Cloud misconfiguration', 'Full names, Email addresses, Cleartext phone numbers, Salted passwords, Guest list contact records', 'Compromised unencrypted database backup archive originating from 2013 discovered circulating on illicit underground forums.', 'Resolved'),
('PBM-500P', '500px Photography Platform System Intrusion', '500px', 'Media', '2018-07-01', '2019-02-08', 14800000, 'Medium', 'Credential Leak', 'Zero-day exploit', 'Usernames, Email addresses, Salted MD5 password hashes, Profile geographic locations', 'Intrusion into production web servers permitted exfiltration of legacy user credential tables.', 'Resolved'),
('PBM-WTPD', 'Wattpad Storytelling Platform User Database Spill', 'Wattpad', 'Media', '2020-06-29', '2020-07-07', 270000000, 'High', 'Credential Leak', 'Zero-day exploit', 'Usernames, Email addresses, Salted bcrypt password hashes, Dates of birth, IP addresses', 'ShinyHunters threat group exploited API misconfiguration to exfiltrate PostgreSQL database tables containing customer information.', 'Resolved'),
('PBM-UAMF', 'Under Armour MyFitnessPal Cloud Data Compromise', 'Under Armour (MyFitnessPal)', 'Retail', '2018-02-01', '2018-03-25', 150000000, 'High', 'Credential Leak', 'Cloud misconfiguration', 'Usernames, Email addresses, Bcrypt & SHA-1 hashed passwords', 'Unauthorized third-party accessed cloud database cluster holding customer account profile tables.', 'Resolved'),
('PBM-MSPC', 'MySpace Legacy User Account Database Leak', 'MySpace', 'Media', '2016-05-01', '2016-05-30', 360000000, 'High', 'Credential Leak', 'Credential stuffing', 'Usernames, Email addresses, Unsalted SHA-1 password hashes', 'Historical compromise of legacy account repository surfaced for sale on dark web marketplace by threat actor Peace_of_Mind.', 'Resolved'),
('PBM-DLMT', 'Dailymotion Video Portal Bcrypt Password Leak', 'Dailymotion', 'Media', '2016-10-01', '2016-12-05', 85000000, 'Medium', 'Credential Leak', 'Zero-day exploit', 'Usernames, Email addresses, Bcrypt password hashes', 'Database breach allowed exfiltration of user tables protected with 10-round bcrypt hashes.', 'Resolved'),
('PBM-HOUZ', 'Houzz Home Design Platform Database Spill', 'Houzz', 'Retail', '2019-01-01', '2019-01-29', 57000000, 'Medium', 'Credential Leak', 'Cloud misconfiguration', 'Usernames, Email addresses, One-way encrypted passwords, Internal user IDs', 'Unauthorized third party obtained an exported data file containing user information.', 'Resolved'),
('PBM-CAES', 'Caesars Entertainment Loyalty Database Extortion', 'Caesars Entertainment', 'Media', '2023-09-07', '2023-09-07', 65000000, 'High', 'MFA Bypass', 'Phishing', 'Social Security Numbers, Driver license numbers, Caesars Rewards loyalty account numbers', 'Social engineering attack against an outsourced IT support vendor allowed threat group to compromise cloud databases.', 'Resolved'),
('PBM-COLP', 'Colonial Pipeline Single-Factor VPN Ransomware', 'Colonial Pipeline', 'Energy', '2021-05-07', '2021-05-07', 100000, 'Critical', 'Credential Leak', 'Credential stuffing', 'Corporate billing records, Employee HR files, Operational control network configurations', 'Compromised password from dark web breach used on inactive legacy VPN profile lacking Multi-Factor Authentication (MFA).', 'Resolved'),
('PBM-META', 'Facebook / Meta Contact Importer Scraping Incident', 'Meta (Facebook)', 'Technology', '2019-04-03', '2021-04-03', 533000000, 'Critical', 'API Exfiltration', 'Zero-day exploit', 'Mobile phone numbers, Facebook profile IDs, Full names, Locations, Birthdates, Email addresses', 'Abuse of mobile contact synchronization feature allowing mass querying of automated phone number ranges without rate limits.', 'Resolved'),
('PBM-JBSF', 'JBS Foods REvil Meat Processing Ransomware', 'JBS Foods', 'Retail', '2021-05-30', '2021-05-30', 500000, 'High', 'Database Exposure', 'Phishing', 'Employee HR records, Financial contracts, Supply logistics databases', 'REvil ransomware gang breached administrative systems via compromised credentials, forcing total factory operational shutdown.', 'Resolved'),
('PBM-ROBN', 'Robinhood Customer Support Voice Social Engineering', 'Robinhood Financial', 'Finance', '2021-11-03', '2021-11-03', 7000000, 'Medium', 'Database Exposure', 'Phishing', 'Customer email addresses, Full names, Phone numbers, Limited debit card details', 'Attacker socially engineered a customer support representative over the phone to obtain authorized access to support administrative tools.', 'Resolved'),
('PBM-NMNM', 'Neiman Marcus Online Retail Account Takeover', 'Neiman Marcus', 'Retail', '2021-09-01', '2021-09-10', 4600000, 'Medium', 'Credential Leak', 'Credential stuffing', 'Payment card numbers, Virtual gift card PINs, Usernames, Passwords, Security questions', 'Credential stuffing attack compromised customer accounts on e-commerce portal, allowing balance exfiltration.', 'Resolved'),
('PBM-DORD', 'DoorDash Third-Party Service Provider Vendor Intrusion', 'DoorDash', 'Retail', '2019-05-04', '2019-09-26', 4900000, 'Medium', 'Database Exposure', 'Supply chain', 'Customer profile data, Delivery addresses, Hashed passwords, Driver license last-4 digits', 'Unauthorized third party accessed data through an integrated third-party customer service vendor.', 'Resolved'),
('PBM-FAFN', 'First American Financial IDOR Title Document Exposure', 'First American Financial', 'Finance', '2019-05-24', '2019-05-24', 885000000, 'Critical', 'Database Exposure', 'Access policy error', 'Bank account numbers, Wire transfer receipts, Social Security Numbers, Mortgage documents, Tax records', 'Insecure Direct Object Reference (IDOR) flaw allowed unauthenticated web users to modify document URL parameter numbers and view arbitrary mortgage files.', 'Resolved'),
('PBM-VRKD', 'Verkada Super Admin Root Camera System Breach', 'Verkada', 'Technology', '2021-03-09', '2021-03-09', 150000, 'High', 'Source Code Leak', 'Access policy error', 'Live surveillance camera video feeds, Customer site lists, Super Admin root credentials', 'Super Admin credentials for internal diagnostic tool discovered publicly exposed on the internet, granting full root video access across hospital and school cameras.', 'Resolved'),
('PBM-MSFT', 'Microsoft Corporate Email Midnight Blizzard Password Spray', 'Microsoft', 'Technology', '2024-01-12', '2024-01-12', 10000, 'High', 'Credential Leak', 'Credential stuffing', 'Executive email correspondence, Internal source code snippets, Customer security secrets', 'Nation-state group Midnight Blizzard (APT29) performed password spray against legacy non-production test tenant lacking MFA, pivoting to corporate mailboxes.', 'Resolved'),
('PBM-DCIO', 'Discord.io MongoDB Custom Invite Database Leak', 'Discord.io', 'Media', '2023-08-14', '2023-08-14', 760000, 'Medium', 'Database Exposure', 'Unpatched vulnerability', 'Usernames, Discord IDs, Email addresses, Salted password hashes, Billing addresses', 'Vulnerability in website code allowed attacker to access MongoDB cluster and dump user tables onto dark web hacking forums.', 'Resolved'),
('PBM-AIND', 'Air India SITA Passenger Service Cloud Cyberattack', 'Air India', 'Transport', '2021-02-21', '2021-03-25', 4500000, 'Medium', 'Database Exposure', 'Supply chain', 'Passport numbers, Credit card data, Frequent flyer data, Ticket issuance records', 'Sophisticated intrusion into global airline IT provider SITA PSS servers compromised 10 years of historical passenger records.', 'Resolved'),
('PBM-CTHY', 'Cathay Pacific Passenger Flight Database Intrusion', 'Cathay Pacific Airways', 'Transport', '2018-03-01', '2018-05-01', 9400000, 'High', 'Database Exposure', 'Stolen session', 'Passenger names, Nationality, Dates of birth, Passport numbers, Historic travel details', 'Unauthorized access to internal reservation servers through compromised administrator accounts.', 'Resolved'),
('PBM-EXPR', 'Experian T-Mobile Credit Applicant Server Intrusion', 'Experian', 'Finance', '2015-09-15', '2015-09-15', 15000000, 'Critical', 'Database Exposure', 'Zero-day exploit', 'Social Security Numbers, Names, Addresses, Dates of birth, Driver license numbers', 'Hackers breached an Experian server holding credit assessment data for T-Mobile USA financing applicants.', 'Resolved'),
('PBM-TRCR', 'Tricare Military Health Unencrypted Backup Tape Theft', 'Tricare (SAIC)', 'Healthcare', '2011-09-14', '2011-09-14', 4900000, 'Medium', 'Database Exposure', 'Access policy error', 'Military patient names, SSNs, Medical diagnosis codes, Prescription histories', 'Unencrypted backup data tapes stolen from a contractor\'s vehicle during transit between government facilities.', 'Resolved'),
('PBM-USOP', 'US Office of Personnel Management (OPM) Clearance Intrusion', 'US Office of Personnel Management', 'Government', '2015-06-04', '2015-06-04', 21500000, 'Critical', 'Database Exposure', 'Stolen session', 'SF-86 security clearance questionnaires, Fingerprint records, Social Security Numbers, Full background investigations', 'Compromised third-party contractor credentials (KeyPoint) allowed state-sponsored actors to bypass multi-factor authentication requirements.', 'Resolved'),
('PBM-SCTR', 'Scottrade Brokerage Client Account Intrusion', 'Scottrade', 'Finance', '2015-10-02', '2015-10-02', 4600000, 'Medium', 'Database Exposure', 'Zero-day exploit', 'Customer names, Physical addresses, Encrypted passwords, Social Security Numbers', 'Cyber intrusion into network database storing non-trading client contact information.', 'Resolved'),
('PBM-CHSI', 'Community Health Systems Heartbleed OpenSSL Intrusion', 'Community Health Systems', 'Healthcare', '2014-08-18', '2014-08-18', 4500000, 'High', 'Session Hijack', 'Unpatched vulnerability', 'Patient names, Addresses, Birth dates, Telephone numbers, Social Security Numbers', 'Exploitation of Heartbleed bug (CVE-2014-0160) on perimeter VPN devices captured active employee session cookies.', 'Resolved'),
('PBM-CRFS', 'CareFirst BlueCross BlueShield Cyber Attack', 'CareFirst BlueCross BlueShield', 'Healthcare', '2015-05-20', '2015-05-20', 1100000, 'Medium', 'Database Exposure', 'Phishing', 'Member names, Usernames, Dates of birth, Email addresses, Subscriber IDs', 'Sophisticated spear phishing attack gained access to member portal registration database.', 'Resolved'),
('PBM-WPRS', 'WordPress / VaultPress Backup API Credential Leak', 'Automattic (VaultPress)', 'Technology', '2022-04-01', '2022-04-05', 1000000, 'Medium', 'API Exfiltration', 'API Key leak', 'Website database backups, WordPress admin hashes, Configuration files', 'Stolen API access keys allowed unauthorized export of customer site snapshots.', 'Resolved'),
('PBM-CDCV', 'Codecov Bash Uploader Supply Chain Token Exfiltration', 'Codecov', 'Technology', '2021-04-01', '2021-04-15', 29000, 'Critical', 'Supply Chain Breach', 'Supply chain', 'CI/CD environmental secrets, Git access tokens, Cloud provider private keys', 'Attacker modified official Bash Uploader script in Docker image, exfiltrating all CI/CD environmental variables passing through test pipelines.', 'Resolved'),
('PBM-CRCL', 'CircleCI Engineer Workstation Session Token Theft', 'CircleCI', 'Technology', '2023-01-04', '2023-01-04', 15000, 'High', 'Session Hijack', 'Stolen session', 'Customer production tokens, AWS keys, Database credentials stored in CI environment variables', 'Malware on engineer laptop stole valid SSO session cookies, bypassing hardware 2FA and accessing production databases.', 'Resolved'),
('PBM-KSYA', 'Kaseya VSA Zero-Day Ransomware Supply Chain Wave', 'Kaseya', 'Technology', '2021-07-02', '2021-07-02', 1500, 'Critical', 'Supply Chain Breach', 'Zero-day exploit', 'MSP customer files, Local system credentials, Active Directory databases', 'Zero-day authentication bypass and SQL injection vulnerability in VSA remote management software exploited by REvil to deploy ransomware across 1,500 downstream clients.', 'Resolved'),
('PBM-MCHP', 'Mailchimp Social Engineering & Crypto Account Targeting', 'Mailchimp (Intuit)', 'Technology', '2022-04-04', '2022-04-04', 106, 'Medium', 'Credential Leak', 'Phishing', 'Email audience contact lists, Campaign templates, API keys', 'Social engineering attack against internal employee credentials allowed threat actors to access customer account tools.', 'Resolved'),
('PBM-TWLO', 'Twilio 0ktapus SMS Phishing Employee Gateway Breach', 'Twilio', 'Telecommunications', '2022-08-04', '2022-08-04', 125, 'Medium', 'Credential Leak', 'Phishing', 'Internal customer records, Authy two-factor registration tokens, SMS routing logs', 'Sophisticated SMS phishing (smishing) campaign tricked employees into providing credentials on spoofed Okta authentication pages.', 'Resolved'),
('PBM-CLDF', 'Cloudflare Stolen Okta Credentials Pivot Attempt', 'Cloudflare', 'Technology', '2023-11-14', '2023-11-23', 5000, 'High', 'Credential Leak', 'Stolen session', 'Internal Atlassian Jira tickets, Confluence wiki documentation, Bitbucket source code', 'Nation-state actor used four compromised credentials and an API token stolen from the earlier Okta customer support portal breach.', 'Resolved'),
('PBM-GRMM', 'Grammarly Chrome Extension Auth Token Vulnerability', 'Grammarly', 'Technology', '2018-02-02', '2018-02-02', 22000000, 'Medium', 'API Exfiltration', 'Zero-day exploit', 'Authentication tokens, User document text, Profile settings', 'Browser extension bug exposed authentication tokens to any website visited, permitting unauthorized access to user cloud documents.', 'Resolved'),
('PBM-GTHB', 'GitHub Stolen Third-Party OAuth App Tokens', 'GitHub', 'Technology', '2022-04-12', '2022-04-12', 100000, 'Medium', 'API Exfiltration', 'Stolen session', 'Private repository source code, Secrets in commits, CI/CD configs', 'Stolen OAuth tokens issued to third-party integrators Heroku and Travis-CI used to download private GitHub repositories.', 'Resolved'),
('PBM-TRLO', 'Trello Public User Profile API Enumeration Dump', 'Trello (Atlassian)', 'Technology', '2024-01-16', '2024-01-16', 15000000, 'Medium', 'API Exfiltration', 'Access policy error', 'Email addresses, Full names, Usernames, Associated Trello board IDs', 'Unauthenticated API endpoint permitted automated enumeration linking email addresses to public Trello user profile records.', 'Resolved'),
('PBM-DELL', 'Dell Technologies Customer Order Portal API Scrape', 'Dell Technologies', 'Technology', '2024-05-08', '2024-05-08', 49000000, 'High', 'API Exfiltration', 'API Key leak', 'Customer names, Physical addresses, Dell hardware service tags, Order item details', 'Threat actor registered multiple partner accounts to brute-force query customer order database APIs without rate throttling.', 'Resolved'),
('PBM-PNDB', 'PandaBuy E-Commerce Leaky API Database Dump', 'PandaBuy', 'Retail', '2024-03-31', '2024-03-31', 1300000, 'Medium', 'Database Exposure', 'Zero-day exploit', 'First and last names, Phone numbers, Email addresses, Delivery addresses, Order records', 'Multiple critical vulnerabilities in website API endpoints and internal systems allowed complete customer order database exfiltration.', 'Resolved'),
('PBM-MDSC', 'MediSecure National E-Prescription Ransomware', 'MediSecure', 'Healthcare', '2024-05-16', '2024-05-16', 12900000, 'Critical', 'Database Exposure', 'Zero-day exploit', 'Patient medical prescription data, Full names, Date of birth, Medicare numbers, Prescribing doctor names', 'Ransomware cyber security incident originated from a third-party vendor database hosting electronic prescription records.', 'Resolved'),
('PBM-CDKG', 'CDK Global BlackSuit Auto Dealership Ransomware', 'CDK Global', 'Technology', '2024-06-19', '2024-06-19', 15000, 'Critical', 'Supply Chain Breach', 'Phishing', 'Automotive sales contracts, Customer credit applications, Employee records', 'BlackSuit ransomware cyberattack knocked core dealer management systems offline for nearly two weeks across 15,000 car dealerships.', 'Resolved'),
('PBM-SYNV', 'Syniverse Undetected Five-Year Telecom Database Access', 'Syniverse', 'Telecommunications', '2021-09-27', '2021-09-27', 500000000, 'Critical', 'Database Exposure', 'Stolen session', 'SMS text message metadata, Call detail records, International roaming logs, Carrier subscriber IDs', 'Unauthorized threat actor maintained persistent credentials on internal database servers for over 5 years without detection.', 'Resolved'),
('PBM-VFIT', 'Vodafone Italy Reseller Portal SIM Swapping Breach', 'Vodafone Italy', 'Telecommunications', '2022-09-08', '2022-09-08', 2000000, 'Medium', 'Credential Leak', 'Credential stuffing', 'Customer ID cards, Tax codes, Contact phone numbers, Contract details, SIM serial numbers', 'Dealer reseller portal credentials compromised to harvest customer identification files for illicit SIM swap operations.', 'Resolved'),
('PBM-ORNG', 'Orange Spain RPKI Admin Infostealer Hijack', 'Orange Spain', 'Telecommunications', '2024-01-03', '2024-01-03', 1000000, 'High', 'MFA Bypass', 'Credential stuffing', 'BGP route configurations, RPKI certificates, Autonomous System (AS) routing tables', 'Infostealer malware on employee PC captured RIPE NCC admin credentials for Orange Spain AS12479 lacking MFA, allowing rogue BGP route announcements.', 'Resolved'),
('PBM-CSCO', 'Cisco Systems Voice Phishing & VPN MFA Fatigue', 'Cisco Systems', 'Technology', '2022-08-10', '2022-08-10', 2800000, 'High', 'MFA Bypass', 'Phishing', 'Internal non-sensitive engineering documents, Box cloud storage files, Active Directory schema', 'Yanluowang threat actors performed voice phishing (vishing) and MFA push notification fatigue against employee personal Google account.', 'Resolved'),
('PBM-ATNT', 'AT&T Snowflake Call & Text Metadata Exfiltration', 'AT&T', 'Telecommunications', '2024-04-14', '2024-07-12', 110000000, 'Critical', 'Database Exposure', 'Credential stuffing', 'Call logs, SMS interaction records, Cellular phone numbers, Cell tower location IDs', 'Compromised contractor credentials used to download customer call interaction database workspace hosted on Snowflake workspace lacking MFA.', 'Resolved');

-- -----------------------------------------------------------------------------
-- Insert 12 Landmark Real-World Case Studies
-- -----------------------------------------------------------------------------
INSERT INTO `case_studies` (`breach_id`, `title`, `subtitle`, `date`, `severity`, `executive_summary`, `timeline_json`, `response`, `attack_vector_tags`, `root_cause`, `data_exposed_tags`, `impact_metrics`, `lessons_learned`) VALUES
('PBM-EQFX', 'Equifax Data Breach Case Study', 'Unpatched Apache Struts CVE-2017-5638 Analysis · 13 May 2017', '2017-05-13', 'Critical', 'In 2017, credit bureau Equifax suffered one of the most severe data compromises in history, exposing highly sensitive personal and financial identifiers of 147 million consumers. The intrusion occurred via an unpatched Apache Struts vulnerability (CVE-2017-5638) on an online dispute portal that had been disclosed months earlier by US-CERT.', '[{\"time\": \"2017-03-07\", \"title\": \"CVE-2017-5638 Disclosed\", \"description\": \"Apache releases patch for remote code execution vulnerability; US-CERT sends critical advisory.\"}, {\"time\": \"2017-03-09\", \"title\": \"Patch Missed in Scan\", \"description\": \"Equifax internal security scanners fail to detect vulnerable Struts libraries on public dispute portal.\"}, {\"time\": \"2017-05-13\", \"title\": \"Initial Attacker Access\", \"description\": \"Chinese military hackers execute commands via OGNL injection and establish persistent web shells.\"}, {\"time\": \"2017-07-29\", \"title\": \"Detection via Expired Cert Renewal\", \"description\": \"Equifax IT updates an expired SSL inspection certificate and immediately observes suspicious exfiltration traffic.\"}, {\"time\": \"2017-09-07\", \"title\": \"Public Disclosure\", \"description\": \"Equifax announces breach of 143M (later revised to 147M) records, resulting in C-suite resignations and $575M FTC settlement.\"}]', 'Equifax isolated affected systems, engaged Mandiant for forensic incident response, replaced executive leadership, implemented enterprise-wide asset discovery, and entered a $575M settlement with the FTC, CFPB, and 50 states.', 'Unpatched vulnerability, Apache Struts, Web Shell, Lateral Movement', 'Failure to patch known critical CVE-2017-5638 within 48-hour internal SLA, lack of network segmentation between web tier and core databases, and expired SSL inspection certificates blinding IDS/IPS monitoring for 10 months.', 'Social Security Numbers, Full names, Dates of birth, Home addresses, Driver license numbers, Credit card numbers', '{\"records\": \"147M\", \"exposure_window\": \"76 days\", \"sessions_reset\": \"N/A\", \"regulatory_fines\": \"$575M\", \"plaintext_passwords\": \"0\"}', 'Enforce rigorous automated patch management policies, maintain active certificate lifecycle tracking for security monitoring appliances, and implement zero-trust network micro-segmentation around sensitive credit databases.'),
('PBM-CPO1', 'Capital One Cloud Storage SSRF Case Study', 'AWS IAM Role Abuse & WAF SSRF Analysis · 22 March 2019', '2019-03-22', 'Critical', 'A former cloud software engineer exploited a Server-Side Request Forgery (SSRF) flaw on a misconfigured open-source Web Application Firewall (WAF) deployed on AWS EC2. The attacker queried the AWS Instance Metadata Service (IMDSv1) to acquire temporary IAM role credentials, subsequently listing and downloading 106 million credit card applications stored in S3 buckets.', '[{\"time\": \"2019-03-22\", \"title\": \"SSRF Exploitation\", \"description\": \"Attacker discovers misconfigured ModSecurity WAF proxy and sends forged request to 169.254.169.254 to harvest IAM role tokens.\"}, {\"time\": \"2019-04-21\", \"title\": \"Mass S3 Sync Exfiltration\", \"description\": \"Using harvested credentials, attacker runs automated aws s3 sync commands to extract over 700 S3 buckets.\"}, {\"time\": \"2019-07-17\", \"title\": \"External Tip Received\", \"description\": \"A security researcher emails Capital One security operations after finding breach artifacts posted to GitHub.\"}, {\"time\": \"2019-07-29\", \"title\": \"FBI Arrest & Indictment\", \"description\": \"Federal authorities arrest the perpetrator; Capital One publicly discloses breach and faces $80M OCC civil penalty.\"}]', 'Capital One patched the WAF proxy configuration, restricted IAM role permissions, rotated all cloud access keys, migrated workloads to IMDSv2 (requiring session tokens), and overhauled cloud security posture management.', 'Cloud misconfiguration, SSRF, IAM Privilege Abuse, AWS Metadata Service', 'Permissive WAF reverse proxy vulnerable to SSRF, combined with over-privileged IAM EC2 instance role having excessive S3 read permissions across hundreds of unrelated customer buckets.', 'Credit card applications, Social Security Numbers, Linked bank account numbers, Credit scores, Transaction records', '{\"records\": \"106M\", \"exposure_window\": \"117 days\", \"sessions_reset\": \"100%\", \"regulatory_fines\": \"$80M\", \"plaintext_passwords\": \"0\"}', 'Enforce AWS IMDSv2 globally to neutralize SSRF metadata token theft, practice strict least-privilege IAM scoping for compute instances, and use automated data loss prevention (DLP) on S3 egress.'),
('PBM-YAHO', 'Yahoo! Global Account Breach Case Study', 'State-Sponsored Phishing & Forged Cookie Incident · August 2013', '2013-08-01', 'Critical', 'In the largest data breach in history, all 3 billion Yahoo accounts were compromised. State-sponsored threat actors gained access through spear-phishing and reverse-engineered Yahoo\'s proprietary account management software, creating cryptographic keys to mint forged browser cookies that bypassed password authentication entirely.', '[{\"time\": \"2013-08-01\", \"title\": \"Database Infiltration\", \"description\": \"Attackers gain internal access and exfiltrate user database containing 3 billion account records.\"}, {\"time\": \"2014-11-01\", \"title\": \"Proprietary Cookie Minting\", \"description\": \"Threat actors reverse-engineer account system to generate forged authentication cookies for 32M specific accounts.\"}, {\"time\": \"2016-09-22\", \"title\": \"Initial 500M Disclosure\", \"description\": \"Yahoo publicly reports 2014 incident affecting 500 million users during Verizon acquisition negotiations.\"}, {\"time\": \"2017-10-03\", \"title\": \"Full Scope Revision to 3B\", \"description\": \"Forensic audit confirms all 3 billion existing Yahoo accounts were affected by 2013 breach, leading to $35M SEC penalty.\"}]', 'Invalidated unencrypted security questions, forced global password resets, revoked forged cookie generation keys, and settled SEC charges for $35M alongside a $117.5M class action settlement.', 'Phishing, Forged Cookies, State-sponsored, Cryptographic Key Theft', 'Spear phishing compromised employee access, allowing threat actors to steal internal user database backups and proprietary cookie-minting cryptographic keys.', 'Usernames, Email addresses, Telephone numbers, MD5 / bcrypt password hashes, Dates of birth, Security questions and answers', '{\"records\": \"3.0B\", \"exposure_window\": \"3+ years\", \"sessions_reset\": \"100%\", \"regulatory_fines\": \"$35M (SEC) + $117.5M\", \"plaintext_passwords\": \"0\"}', 'Never rely on static security questions, employ hardware-backed HSMs for session signing keys, and mandate transparent executive escalation for threat intelligence.'),
('PBM-LPAS', 'LastPass Cloud Vault Exfiltration Case Study', 'DevOps Engineer Endpoint Compromise · August–November 2022', '2022-08-12', 'Critical', 'A sophisticated threat actor compromised a senior DevOps engineer\'s personal computer by exploiting an unpatched Plex Media Server vulnerability (CVE-2020-5741). The attacker installed keyloggers to capture master AWS IAM access tokens, subsequently exfiltrating encrypted customer password vault backups from cloud storage.', '[{\"time\": \"2022-08-12\", \"title\": \"Developer Environment Breach\", \"description\": \"Attackers gain initial access to LastPass development environment using compromised developer credentials.\"}, {\"time\": \"2022-10-15\", \"title\": \"DevOps Home Workstation Compromise\", \"description\": \"Attacker exploits Plex vulnerability on DevOps engineer home computer, deploying keylogger to steal master cloud keys.\"}, {\"time\": \"2022-11-30\", \"title\": \"Production Cloud Vault Exfiltration\", \"description\": \"Attackers access AWS S3 buckets containing encrypted customer password vault backups and account metadata.\"}, {\"time\": \"2023-03-01\", \"title\": \"Comprehensive Post-Mortem\", \"description\": \"LastPass publishes final advisory detailing the multi-stage attack and recommended master password updates.\"}]', 'LastPass rotated critical AWS credentials, deployed endpoint detection & response (EDR) to all personal/remote workstations, and mandated strict device compliance policies for infrastructure access.', 'Supply chain, Home Workstation Compromise, Keylogger, AWS S3 Exfiltration', 'Targeted exploitation of third-party software on an engineer\'s home computer, allowing keylogging of credentials with access to cloud backup decryption secrets.', 'Encrypted password vaults, Website URLs, Account usernames, Billing addresses, End-user telephone numbers', '{\"records\": \"30M\", \"exposure_window\": \"110 days\", \"sessions_reset\": \"100%\", \"regulatory_fines\": \"Pending Litigation\", \"plaintext_passwords\": \"0\"}', 'Enforce strict BYOD/work-from-home endpoint isolation, require hardware FIDO2 keys for all cloud infrastructure access, and encrypt URL metadata inside password vaults.'),
('PBM-23ME', '23andMe Credential Stuffing & Scraping Case Study', 'Account Takeover & DNA Relatives Scraping · October 2023', '2023-10-01', 'High', 'Attackers executed automated credential stuffing attacks against 23andMe customer accounts using credential pairs stolen from unrelated third-party breaches. By compromising roughly 14,000 accounts without MFA, the attackers abused the \'DNA Relatives\' opt-in feature to scrape the genetic and family tree data of 6.9 million individuals.', '[{\"time\": \"2023-08-15\", \"title\": \"Credential Stuffing Wave\", \"description\": \"Threat actors execute credential stuffing against accounts with reused passwords lacking MFA.\"}, {\"time\": \"2023-10-01\", \"title\": \"Data Listed on Hacking Forum\", \"description\": \"Attacker Golem publishes sample genetic profile records of Ashkenazi and Chinese ancestry on BreachForums.\"}, {\"time\": \"2023-10-06\", \"title\": \"23andMe Security Notice\", \"description\": \"Company begins investigating and disables DNA Relatives feature while initiating global password resets.\"}, {\"time\": \"2023-12-01\", \"title\": \"SEC 8-K Disclosure\", \"description\": \"23andMe files 8-K disclosing 6.9M total users affected via DNA Relatives network scraping.\"}]', 'Disabled DNA Relatives feature temporarily, mandated two-step verification (2FA) for all users, forced password resets, and implemented advanced bot detection rules on login endpoints.', 'Credential stuffing, MFA Bypass, API Scraping, Feature Abuse', 'Lack of mandatory Multi-Factor Authentication and absence of rate-limiting or anomalous scraping controls on the DNA Relatives network linkage feature.', 'Genetic ancestry reports, Family tree linkages, Full names, Birth years, Geographical locations, Self-reported health traits', '{\"records\": \"6.9M\", \"exposure_window\": \"60 days\", \"sessions_reset\": \"100%\", \"regulatory_fines\": \"$30M Settlement\", \"plaintext_passwords\": \"0\"}', 'Mandate Multi-Factor Authentication by default on sensitive health/identity platforms, and implement strict graph-query rate limits on social discovery features.'),
('PBM-MRRT', 'Marriott Starwood Guest Reservation Case Study', 'Legacy RAT & Lateral Movement Breach · 2014–2018', '2014-07-01', 'Critical', 'Prior to Marriott acquiring Starwood Hotels in 2016, Starwood\'s IT network was compromised by threat actors who installed Remote Access Trojans (RATs) and Mimikatz. The attackers maintained undetected persistence for over four years, exfiltrating 339 million guest reservation records.', '[{\"time\": \"2014-07-01\", \"title\": \"Initial Starwood Compromise\", \"description\": \"Attackers deploy web shells and RATs inside Starwood guest reservation infrastructure.\"}, {\"time\": \"2016-09-23\", \"title\": \"Marriott Acquisition\", \"description\": \"Marriott closes Starwood acquisition without conducting comprehensive deep-packet security audits on legacy network.\"}, {\"time\": \"2018-09-08\", \"title\": \"Accenture Guardium Alert\", \"description\": \"Internal database monitoring detects anomalous query trying to export master reservation table.\"}, {\"time\": \"2018-11-30\", \"title\": \"Public Disclosure\", \"description\": \"Marriott publicly discloses breach of 339M guest records and is fined £18.4M by UK ICO under GDPR.\"}]', 'Decommissioned legacy Starwood reservation database, accelerated migration to secure Marriott cloud, deployed enterprise EDR agents, and settled GDPR penalties.', 'Stolen session, RAT, Mimikatz, M&A Supply Chain', 'Inadequate cybersecurity due diligence during M&A integration, allowing a pre-existing four-year persistence compromise in legacy network to remain undetected.', 'Passport numbers, Contact info, Loyalty account details, Travel itinerary, Encrypted payment card numbers', '{\"records\": \"339M\", \"exposure_window\": \"4.2 years\", \"sessions_reset\": \"N/A\", \"regulatory_fines\": \"£18.4M (ICO)\", \"plaintext_passwords\": \"0\"}', 'Conduct comprehensive red-team compromise assessments and baseline threat-hunting before interconnecting corporate networks during mergers and acquisitions.'),
('PBM-TRGT', 'Target Corporation HVAC Vendor POS Case Study', 'Third-Party Credential Phishing & BlackPOS Malware · Nov 2013', '2013-11-27', 'Critical', 'Cybercriminals stole network credentials from a third-party HVAC contractor (Fazio Mechanical) via email phishing. Because Target\'s network lacked segmentation between billing and in-store operations, the attackers pivoted to Point-of-Sale (POS) systems, deploying BlackPOS memory-scraping malware that captured 110 million customer credit cards and personal records.', '[{\"time\": \"2013-10-04\", \"title\": \"Vendor Phishing Email\", \"description\": \"Fazio Mechanical Services employee opens malicious Citadel Trojan email; vendor credentials stolen.\"}, {\"time\": \"2013-11-15\", \"title\": \"Target Network Access\", \"description\": \"Attackers log in via vendor billing portal and traverse internal network to POS domain controllers.\"}, {\"time\": \"2013-11-27\", \"title\": \"BlackPOS Malware Deployment\", \"description\": \"BlackPOS memory-scraping malware deployed across thousands of cash registers ahead of Black Friday.\"}, {\"time\": \"2013-12-12\", \"title\": \"US DOJ / Secret Service Alert\", \"description\": \"Federal law enforcement notifies Target of massive card theft; Target disables malware and discloses incident.\"}]', 'Fired executive leadership, accelerated nationwide EMV chip-and-PIN terminal rollout, established dedicated Security Operations Center, and paid $18.5M multistate settlement.', 'Phishing, Third-Party Supply Chain, POS Memory Scraping, Lateral Movement', 'Flat network architecture with no network segmentation between external contractor vendor portals and internal PCI-DSS payment environments.', 'Credit & debit card magnetic stripe data, Customer names, Mailing addresses, Phone numbers, Email addresses', '{\"records\": \"110M\", \"exposure_window\": \"16 days\", \"sessions_reset\": \"100%\", \"regulatory_fines\": \"$18.5M Multistate\", \"plaintext_passwords\": \"0\"}', 'Implement strict firewall isolation and zero-trust micro-segmentation between third-party vendor access pathways and sensitive payment processing networks.'),
('PBM-UBER', 'Uber GitHub Credential & AWS S3 Case Study', 'Hardcoded Code Secrets & Ransom Payoff Analysis · October 2016', '2016-10-01', 'High', 'Attackers discovered hardcoded Amazon Web Services (AWS) credentials in a private GitHub repository used by Uber software engineers. Using these keys, attackers accessed Uber\'s AWS S3 bucket backups and exfiltrated records for 57 million riders and drivers, subsequently demanding a $100,000 extortion payment disguised as a bug bounty.', '[{\"time\": \"2016-10-01\", \"title\": \"GitHub Secret Discovery\", \"description\": \"Attackers scan Uber private GitHub repositories and extract plaintext AWS access tokens.\"}, {\"time\": \"2016-10-15\", \"title\": \"AWS S3 Database Exfiltration\", \"description\": \"Attackers download S3 archives holding 57 million user records and 600,000 driver license files.\"}, {\"time\": \"2016-11-10\", \"title\": \"Extortion Demand\", \"description\": \"Attackers contact Uber executive security team demanding $100k payoff to delete data.\"}, {\"time\": \"2017-11-21\", \"title\": \"Public Disclosure & CSO Conviction\", \"description\": \"New leadership discloses incident; former CSO is later criminally convicted for breach concealment.\"}]', 'Overhauled code secrets scanning, rotated AWS access keys, settled with FTC and state AGs for $148M, and established formal whistleblower and disclosure compliance procedures.', 'API Key leak, GitHub Secret Exposure, S3 Exfiltration, Extortion', 'Hardcoded cloud credentials in version control repositories combined with single-factor AWS access keys lacking IP restrictions or IAM boundary policies.', 'Driver license numbers, Rider names, Email addresses, Mobile phone numbers', '{\"records\": \"57M\", \"exposure_window\": \"40 days\", \"sessions_reset\": \"100%\", \"regulatory_fines\": \"$148M Settlement\", \"plaintext_passwords\": \"0\"}', 'Enforce pre-commit automated secret scanning in all developer pipelines and use ephemeral IAM credentials via AWS STS rather than static access keys.'),
('PBM-SLRW', 'SolarWinds SUNBURST Supply Chain Case Study', 'Build System Code Injection & SAML Golden Ticket Incident · 2020', '2020-03-01', 'Critical', 'In one of the most sophisticated supply chain operations in cyber history, Russian APT29 hackers compromised the build environment of SolarWinds Orion software. They injected a stealthy backdoor (SUNBURST) into legitimate signed DLL updates, which were automatically distributed to over 18,000 enterprise and US government networks.', '[{\"time\": \"2019-09-04\", \"title\": \"Initial Build Access\", \"description\": \"Threat actors access SolarWinds software development environment to test stealthy injection techniques.\"}, {\"time\": \"2020-02-20\", \"title\": \"SUNBURST Injection\", \"description\": \"Malicious SolarWinds.Orion.Core.BusinessLayer.dll injected into official Orion build pipeline.\"}, {\"time\": \"2020-03-26\", \"title\": \"Trojanized Release\", \"description\": \"Digitally signed updates pushed to 18,000 customers including US Treasury, Homeland Security, and Fortune 500.\"}, {\"time\": \"2020-12-12\", \"title\": \"FireEye Discovers Backdoor\", \"description\": \"FireEye uncovers compromise after detecting unauthorized MFA registration on their own corporate network.\"}]', 'SolarWinds released clean Orion builds, rebuilt entire software development environment with reproducible builds (CISA SBOM standards), and revoked compromised code-signing certificates.', 'Supply chain, Build Pipeline Injection, Nation-state, Golden SAML', 'Compromised build server lacking isolated ephemeral build agents, allowing malware to modify source code in memory during compilation before digital signing.', 'Internal emails, System configuration files, Network topologies, SAML signing certificates', '{\"records\": \"18K Orgs\", \"exposure_window\": \"9 months\", \"sessions_reset\": \"100%\", \"regulatory_fines\": \"SEC Enforcement Action\", \"plaintext_passwords\": \"0\"}', 'Adopt Software Bill of Materials (SBOM), implement dual-pipeline reproducible software builds with zero network connectivity during compilation, and protect SAML token signing keys.'),
('PBM-CHNG', 'Change Healthcare Ransomware Case Study', 'Single-Factor Citrix Portal ALPHV BlackCat Intrusion · Feb 2024', '2024-02-21', 'Critical', 'ALPHV/BlackCat ransomware operators gained access to Change Healthcare\'s network using stolen corporate credentials on a Citrix remote access portal that lacked Multi-Factor Authentication (MFA). The attack disrupted prescription billing across thousands of US pharmacies and exposed sensitive medical records of 100 million individuals.', '[{\"time\": \"2024-02-12\", \"title\": \"Citrix Portal Log-in\", \"description\": \"Threat actors use valid stolen employee credentials to access external Citrix portal without MFA challenge.\"}, {\"time\": \"2024-02-19\", \"title\": \"Mass Data Exfiltration\", \"description\": \"Attackers exfiltrate 6 terabytes of healthcare records and insurance claim databases.\"}, {\"time\": \"2024-02-21\", \"title\": \"Ransomware Encryption\", \"description\": \"ALPHV deploys BlackCat ransomware, encrypting core clearinghouse servers and causing nationwide healthcare outage.\"}, {\"time\": \"2024-03-01\", \"title\": \"$22M Ransom Paid\", \"description\": \"Parent company UnitedHealth pays $22 million Bitcoin ransom; OCR launches federal investigation.\"}]', 'UnitedHealth Group advanced billions in emergency funding to impacted healthcare providers, isolated legacy systems, mandated universal MFA enforcement, and rebuilt clearinghouse infrastructure.', 'Stolen session, No MFA, Citrix Portal, Ransomware, Extortion', 'Failure to enforce Multi-Factor Authentication (MFA) across all external-facing remote access endpoints and legacy enterprise portals.', 'Patient medical histories, Diagnosis codes, Health insurance claim numbers, Social Security Numbers, Billing records', '{\"records\": \"100M\", \"exposure_window\": \"9 days\", \"sessions_reset\": \"100%\", \"financial_impact\": \"$2.3B Total Recovery\", \"plaintext_passwords\": \"0\"}', 'Enforce zero-exception hardware MFA across 100% of corporate remote access gateways and maintain air-gapped immutable backup recovery systems.'),
('PBM-SNOW', 'Snowflake Infostealer Campaigns Case Study', 'Contractor Malware & Ticketmaster / AT&T Exfiltration · May 2024', '2024-05-27', 'Critical', 'Threat actor group UNC5537 targeted over 165 corporate organizations using Snowflake cloud data warehouses (including Ticketmaster, AT&T, and Santander). The attackers used infostealer malware (Lumma/RedLine) to steal credentials from contractor personal computers and accessed corporate Snowflake tenants that lacked Multi-Factor Authentication and network allowlists.', '[{\"time\": \"2024-04-14\", \"title\": \"Infostealer Harvesting\", \"description\": \"Attackers obtain contractor Snowflake credentials through infostealer logs on illicit Telegram channels.\"}, {\"time\": \"2024-05-20\", \"title\": \"Automated Data Exfiltration\", \"description\": \"Attackers execute automated SQL queries across multiple enterprise tenants to dump customer tables.\"}, {\"time\": \"2024-05-27\", \"title\": \"Ticketmaster 560M Dump\", \"description\": \"ShinyHunters posts 560 million Ticketmaster customer records for sale on BreachForums for $500k.\"}, {\"time\": \"2024-06-05\", \"title\": \"Mandiant & Snowflake Joint Report\", \"description\": \"Mandiant confirms UNC5537 credential campaign targeting single-factor Snowflake instances lacking MFA.\"}]', 'Snowflake instituted mandatory MFA policies and enhanced IP network policy controls; impacted organizations notified millions of affected customers and rotated credentials.', 'Credential stuffing, Infostealer Malware, No MFA, Cloud Data Warehouse', 'Corporate Snowflake tenants permitted single-factor password logins without enforcing organization-wide MFA or IP allowlisting.', 'Customer names, Email addresses, Billing addresses, Telephone numbers, Partial payment card digits & expiration dates', '{\"records\": \"560M+\", \"exposure_window\": \"45 days\", \"sessions_reset\": \"100%\", \"affected_tenants\": \"165+ Organizations\", \"plaintext_passwords\": \"0\"}', 'Mandate Single Sign-On (SSO) with Phishing-Resistant MFA (FIDO2) for all SaaS/Data Warehouse accounts, and enforce IP access allowlists on critical cloud repositories.'),
('PBM-CNVA', 'Canva Graphic Design Gnosticplayers Case Study', 'Administrative Gateway Vulnerability & Bcrypt Exposure · May 2019', '2019-05-24', 'High', 'Popular graphic design platform Canva was breached by serial threat actor Gnosticplayers. The attacker bypassed perimeter controls through an administrative gateway vulnerability, exfiltrating account records and salted bcrypt password hashes for 137 million users before being contained.', '[{\"time\": \"2019-05-24 · 06:13 UTC\", \"title\": \"Administrative Gateway Exploit\", \"description\": \"Attacker identifies and exploits vulnerability in internal administrative proxy endpoint.\"}, {\"time\": \"2019-05-24 · 07:45 UTC\", \"title\": \"Database Exfiltration\", \"description\": \"Attacker dumps customer profile tables and salted bcrypt password hashes.\"}, {\"time\": \"2019-05-24 · 11:00 UTC\", \"title\": \"Intrusion Contained\", \"description\": \"Canva security team identifies unauthorized access, revokes credentials, and blocks entry vectors.\"}, {\"time\": \"2019-05-25\", \"title\": \"Transparent Customer Advisory\", \"description\": \"Canva proactively emails all affected users, urging password changes and OAuth token invalidation.\"}]', 'Canva rapidly closed the administrative gateway vulnerability, invalidated active OAuth tokens, forced password resets, and engaged external forensics to verify containment.', 'Zero-day exploit, Administrative Gateway, Database Exfiltration, Bcrypt', 'Improper access control and vulnerability on an internal administrative management gateway exposed to network ingress.', 'Usernames, Real names, Email addresses, Salted bcrypt password hashes, City/Country locations', '{\"records\": \"137M\", \"exposure_window\": \"5 hours\", \"sessions_reset\": \"100%\", \"plaintext_passwords\": \"0\"}', 'Use modern cryptographic hashing (salted bcrypt or Argon2id) to protect passwords in the event of database exfiltration, and ensure administrative gateways require VPN/zero-trust access.');

-- -----------------------------------------------------------------------------
-- Insert Verified Regulatory Sources & Citations
-- -----------------------------------------------------------------------------
INSERT INTO `sources` (`breach_id`, `source_type`, `title`, `authority_or_publisher`, `url`, `publication_year`, `citation_note`) VALUES
('PBM-EQFX', 'Regulatory Settlement', 'FTC Settlement with Equifax Over 2017 Data Breach', 'Federal Trade Commission (FTC)', 'https://www.ftc.gov/news-events/news/press-releases/2019/07/ftc-cfpb-and-states-announce-settlement-equifax-over-2017-data-breach', '2019', 'FTC File No. 172 3203 · $575M Settlement'),
('PBM-EQFX', 'DOJ Indictment', 'US Indictment of PLA Hackers for 2017 Equifax Breach', 'US Department of Justice', 'https://www.justice.gov/opa/pr/chinese-military-personnel-charged-computer-fraud-economic-espionage-and-wire-fraud-hacking', '2020', 'Case 1:20-cr-00030'),
('PBM-CPO1', 'DOJ Conviction', 'Former Tech Worker Convicted in Capital One Cloud Intrusion', 'US Department of Justice (W.D. Wash.)', 'https://www.justice.gov/usao-wdwa/pr/former-seattle-tech-worker-convicted-wire-fraud-and-computer-intrusions', '2022', 'W.D. Wash. Conviction'),
('PBM-CPO1', 'Regulatory Order', 'OCC Civil Money Penalty Order against Capital One ($80M)', 'Office of the Comptroller of the Currency (OCC)', 'https://www.occ.gov/news-issuances/news-releases/2020/nr-occ-2020-101.html', '2020', 'AA-EC-2020-48'),
('PBM-YAHO', 'SEC Enforcement', 'Altaba (f/k/a Yahoo!) $35M Penalty for Cyber Breach Failure to Disclose', 'Securities and Exchange Commission (SEC)', 'https://www.sec.gov/news/press-release/2018-71', '2018', 'Release No. 2018-71'),
('PBM-YAHO', 'DOJ Indictment', 'US Charges Russian FSB Officers in Yahoo! Hack', 'US Department of Justice', 'https://www.justice.gov/opa/pr/us-charges-russian-fsb-officers-and-their-conspirators-hacking-yahoo-and-millions-email-accounts', '2017', 'Indictment No. 17-CR-00103'),
('PBM-LPAS', 'Vendor Advisory', 'LastPass Security Incident Update & Recommended Actions', 'LastPass Security Advisory', 'https://blog.lastpass.com/posts/2023/03/security-incident-update-recommended-actions', '2023', 'Official Technical Post-Mortem'),
('PBM-23ME', 'SEC Filing', '23andMe Holding Co. Form 8-K Disclosure', 'Securities and Exchange Commission (SEC)', 'https://www.sec.gov/edgar/browse/?CIK=0001804591', '2023', 'Form 8-K Dec 2023'),
('PBM-MRRT', 'GDPR Enforcement', 'ICO Fines Marriott International £18.4M for GDPR Violations', 'UK Information Commissioner\'s Office (ICO)', 'https://ico.org.uk/about-the-ico/news-and-events/news-and-blogs/2020/10/ico-fines-marriott-international-inc-184m-for-gdpr-breaches/', '2020', 'Penalty Notice COM0804337'),
('PBM-TRGT', 'Congressional Report', 'A Kill Chain Analysis of the 2013 Target Data Breach', 'US Senate Committee on Commerce, Science & Transportation', 'https://www.commerce.senate.gov', '2014', 'Majority Staff Report'),
('PBM-UBER', 'DOJ Conviction', 'Former Chief Security Officer Of Uber Convicted Of Concealing Breach', 'US Department of Justice (N.D. Cal.)', 'https://www.justice.gov/usao-ndca/pr/former-chief-security-officer-uber-convicted-federal-charges-covering-data-breach', '2022', 'Case 3:20-cr-00375-WHO'),
('PBM-SLRW', 'CISA Advisory', 'Alert AA20-352A: Advanced Persistent Threat Compromise of Infrastructure', 'Cybersecurity & Infrastructure Security Agency (CISA)', 'https://www.cisa.gov/news-events/cybersecurity-advisories/aa20-352a', '2020', 'Emergency Directive 21-01'),
('PBM-CHNG', 'HHS Civil Rights', 'HHS OCR Initiates Investigation into Change Healthcare Cybersecurity Incident', 'US Dept of Health and Human Services (HHS)', 'https://www.hhs.gov/about/news/2024/03/13/hhs-office-civil-rights-initiates-investigation-change-healthcare-cybersecurity-incident.html', '2024', 'HHS OCR Notice'),
('PBM-SNOW', 'Threat Intelligence', 'UNC5537 Targeting Snowflake Customer Database Environments', 'Mandiant / Google Cloud Security', 'https://cloud.google.com/blog/topics/threat-intelligence/unc5537-snowflake-data-theft-extortion', '2024', 'Mandiant Report M-Trends'),
('PBM-CNVA', 'Security Advisory', 'Canva Customer Security Incident Notification', 'Canva Security Advisory / Have I Been Pwned', 'https://haveibeenpwned.com/PwnedWebsites#Canva', '2019', 'HIBP Incident Directory'),
('ALL', 'Breach Index', 'Have I Been Pwned Pwned Websites Directory', 'Have I Been Pwned (Troy Hunt)', 'https://haveibeenpwned.com/PwnedWebsites', '2026', 'Curated Index of Verified Breaches'),
('ALL', 'Threat Report', 'Verizon Data Breach Investigations Report (DBIR)', 'Verizon Threat Research', 'https://www.verizon.com/business/resources/reports/dbir/', '2024', 'Annual Empirical Threat Metric Analysis');
